apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: train-ticket-reservation
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vamsi
  template:
    metadata:
      labels:
        app: vamsi
    spec:
      containers:
        - name: vamsi
          image: nginx
          ports:
            - containerPort: 80  
